export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const USERS_CURRENT_PAGE = 'USERS_CURRENT_PAGE';
export const USERS_PER_PAGE = 'USERS_PER_PAGE';
export const TOTAL_PAGES = 'TOTAL_PAGES';
export const SEARCHING = 'SEARCHING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const RESET = 'RESET';
export const STORING_USER = 'STORING_USER';
export const RESET_FORM = 'RESET_FORM';
export const STORE_USER_ERROR = 'STORE_USER_ERROR';
export const SWITCH_STATUS = 'SWITCH_STATUS';

export const FETCH_ONE_USER_SUCCESS = 'FETCH_ONE_USER_SUCCESS';
export const ONE_USER_REQUEST = 'ONE_USER_REQUEST';
export const FETCH_ONE_USER_ERROR = 'FETCH_ONE_USER_ERROR';